/**
 * Ausfuehrungsschritte je KLV-Position.
 *
 * Quelle: Vorlage "Initialschulung — Umfassende Instruktionen der Pflegende
 * Angehoerige (Anstellung)". Aus der Vorlage strukturiert extrahiert.
 *
 * ACHTUNG: Fachlich noch nicht validiert. Vor Verwendung in einem Nachweis
 * gegenueber einer Krankenkasse muss der Inhalt fachlich geprueft und mit dem
 * offiziellen Leistungskatalog abgeglichen werden.
 *
 * Abgedeckte Positionen: 85
 */

export interface KLVAusfuehrungsschritte {
  /** KLV-Nummer, entspricht `nr` im Leistungskatalog */
  nr: string;
  /** Bezeichnung gemaess Schulungsvorlage (kann vom Katalog abweichen) */
  bezeichnungVorlage: string;
  /** Bereichsgruppe gemaess Schulungsvorlage */
  bereichVorlage: string;
  /** Einzelne Taetigkeitsschritte, in Reihenfolge der Vorlage */
  schritte: string[];
}

export const KLV_AUSFUEHRUNGSSCHRITTE_VORLAGE_VERSION = 'Initialschulung-Vorlage (unvalidiert)';

export const KLV_AUSFUEHRUNGSSCHRITTE: KLVAusfuehrungsschritte[] = [
  {
    nr: '10101',
    bezeichnungVorlage: 'Ganzwäsche bettlägerige Klientin',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Bett vorbereiten und Klientin ausziehen',
      'Klientin waschen und abtrocknen',
      'Hautpflegelotion einreiben (falls notwendig)',
      'Klientin anziehen',
      'Haare kämmen',
      'Bettwäsche wechseln oder Bett neu machen (falls notwendig)',
      'Klientin neu lagern',
    ],
  },
  {
    nr: '10102',
    bezeichnungVorlage: 'Ganzwäsche in Bad, Dusche oder am Lavabo',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Begleitung oder Transfer (Rollstuhl) der Klientin ins Badezimmer',
      'Klientin ausziehen',
      'Klientin in Badewanne/Dusche oder vor Lavabo hinsetzen',
      'Klientin waschen',
      'Rücktransfer aus Badewanne/Dusche',
      'Klientin abtrocknen',
      'Hautpflegelotion einreiben (falls notwendig)',
      'Klientin anziehen und kämmen',
      'Transfer der Klientin aus Badezimmer',
      'Bad oder Dusche reinigen',
    ],
  },
  {
    nr: '10103',
    bezeichnungVorlage: 'Teilwäsche im Bett (inkl. Intimpflege)',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Bett vorbereiten und Nachthemd ausziehen',
      'Körperteile der Klientin waschen und abtrocknen',
      'Intimpflege',
      'Hautpflegelotion einreiben (falls notwendig)',
      'Klientin anziehen',
      'Haare kämmen',
      'Bettwäsche wechseln oder Bett neu machen (falls notwendig)',
    ],
  },
  {
    nr: '10104',
    bezeichnungVorlage: 'Teilwäsche am Lavabo (inkl. Intimpflege)',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Klientin vor dem Lavabo hinsetzen (helfen)',
      'Körperteil waschen und trocknen',
      'Intimpflege',
      'Hautpflegelotion einreiben (falls notwendig)',
      'Haare kämmen',
      'Anziehen',
      'Transfer der Klientin aus dem Badezimmer',
    ],
  },
  {
    nr: '10105',
    bezeichnungVorlage: 'Intimpflege (im Bett oder am Lavabo)',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Bettschutz und Schutz der Kleider / des Nachhemds',
      'Hilfsmittel entfernen (Urinal, Einlagen u.ä.)',
      'Intimpflege durchführen',
      'Hautpflegelotion einreiben (falls notwendig)',
      'Hilfsmittel anlegen (Urinal, Einlagen u.ä.)',
      'Anziehen im Intimbereich und Klientin bequem platzieren',
      'Bettwäsche wechseln (falls notwendig)',
    ],
  },
  {
    nr: '10106',
    bezeichnungVorlage: 'Rasur (in Kombination mit Ganz- oder Teilwäsche)',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Trocken oder feucht rasieren',
      'After Shave einreiben',
    ],
  },
  {
    nr: '10107',
    bezeichnungVorlage: 'Haare waschen',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Vorbereitung der Klientin im Bett oder am Lavabo (inklusive Transfer)',
      'Haare waschen',
      'Haarpflegemittel auftragen, einreiben und spülen (falls notwendig)',
      'Trocknen mit Föhn',
      'Kämmen',
      'Lagerung der Klientin oder Rücktransfer (falls notwendig)',
    ],
  },
  {
    nr: '10108',
    bezeichnungVorlage: 'Nägel schneiden Finger',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Hände der Klientin waschen',
      'Nägel schneiden, reinigen und feilen',
      'Lotion oder Creme auftragen',
    ],
  },
  {
    nr: '10109',
    bezeichnungVorlage: 'Nägel schneiden Zehen',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Füsse der Klientin waschen',
      'Nägel schneiden, reinigen',
      'Lotion oder Creme auftragen',
    ],
  },
  {
    nr: '10110',
    bezeichnungVorlage: 'Nägel schneiden Zehen bei Diabetikern',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Füsse der Klientin waschen und gut trocknen (falls notwen dig)',
      'Nägel schneiden und reinigen',
      'Lotion oder Creme auftragen',
      'Haut an den Füssen kontrollieren und allfällige kleine Läsionen versorgen',
    ],
  },
  {
    nr: '10112',
    bezeichnungVorlage: 'Zahnpflege',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Zahnreinigung',
      'Prothesenreinigung (falls notwendig)',
    ],
  },
  {
    nr: '10113',
    bezeichnungVorlage: 'Mundpflege (z.B.in Palliativsituation)',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Mundpflege bei Klienten, bei welchen normale Zahnpflege nicht möglich ist',
      'Zahn- und Mundreinigung',
      'Prothesenreinigung',
      'Feucht halten der Mundschleimhaut',
    ],
  },
  {
    nr: '10114',
    bezeichnungVorlage: 'Hilfe An-/Auskleiden',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Vorbereitung der Kleider',
      'Unterstützung beim An- oder Ausziehen',
      'Kleider versorgen',
    ],
  },
  {
    nr: '10115',
    bezeichnungVorlage: 'Kompressionsstrümpfe/-verband',
    bereichVorlage: 'Hygiene',
    schritte: [
      'Hautkontrolle',
      'Kompressionsstrümpfe anziehen / Kompressionsverband anlegen',
      'Strümpfe/Hosen anziehen',
      'Kompressionsstrümpfe / Kompressionsverband ausziehen, Hautkontrolle, Hautpflege',
    ],
  },
  {
    nr: '10201',
    bezeichnungVorlage: 'Atemtherapie / Sekret aushusten helfen',
    bereichVorlage: 'Atmung',
    schritte: [
      'Klientin während der Atemübung anleiten',
      'Hilfe beim Aushusten von Sekret',
      'Ausklopfen',
      'Anleitung zu Atemübungen, Atemstimulation',
      'Anleitung zur Apparatebenutzung und Wartung',
      'Atemfrequenzkontrolle und Kontrolle der Brustkastenbewegung',
    ],
  },
  {
    nr: '10202',
    bezeichnungVorlage: 'Inhalation vorbereiten',
    bereichVorlage: 'Atmung',
    schritte: [
      'Medikament in Apparat einfüllen',
      'Funktionstest des Apparats',
      'Anleitung zur korrekten Apparatebenutzung und Wartung',
      'Regelmässige Apparatekontrolle und Apparateunterhalt veranlassen',
    ],
  },
  {
    nr: '10203',
    bezeichnungVorlage: 'Inhalation mit konstanter Präsenz',
    bereichVorlage: 'Atmung',
    schritte: [
      'Medikament in Apparat einfüllen',
      'Funktionstest des Apparats',
      'Anleitung zur korrekten Inhalation und Apparatebenutzung während der ganzen',
      'Inhalationsdauer',
      'Regelmässige Apparatekontrolle und Apparateunterhalt veranlassen',
    ],
  },
  {
    nr: '10204',
    bezeichnungVorlage: 'O2-Verabreichung',
    bereichVorlage: 'Atmung',
    schritte: [
      'O2-Behälter installieren',
      'Aquapak anschliessen',
      'O2-Fluss kontrollieren',
      'Leck ausschliessen',
      'Sonde oder Maske anschliessen',
      'Durchgängigkeit der oberen Atemwege verifizieren',
      'Sonde befestigen oder Maske aufsetzen',
      'Fluss (Liter pro Minute) einstellen',
      'O2-Nachschub sicherstellen',
    ],
  },
  {
    nr: '10205',
    bezeichnungVorlage: 'Absaugen',
    bereichVorlage: 'Atmung',
    schritte: [
      'Absauggerät bereitstellen',
      'Funktionsprüfung des Absauggerätes',
      'Handschuhe anziehen',
      'Klientin richtig lagern',
      'Sekrete absaugen',
      'Absauggerät leeren, reinigen und vorbereiten',
      'Entsorgung der Sekrete',
      'Regelmässige Apparatekontrolle und Apparateunterhalt veranlassen',
    ],
  },
  {
    nr: '10206',
    bezeichnungVorlage: 'Tracheostomapflege',
    bereichVorlage: 'Atmung',
    schritte: [
      'Handschuhe und Mundschutz anziehen',
      'Kanüle entfernen',
      'Haut um das Tracheostoma reinigen und pflegen',
      'Kanüle reinigen',
      'Kanüle einsetzen, Kompressen und Bänder fixieren',
    ],
  },
  {
    nr: '10207',
    bezeichnungVorlage: 'Luftbefeuchter',
    bereichVorlage: 'Atmung',
    schritte: [
      'Luftbefeuchter vorbereiten',
      'Wasserqualität periodisch kontrollieren',
      'Regelmässige Apparatekontrolle und Apparateunterhalt veranlassen',
    ],
  },
  {
    nr: '10301',
    bezeichnungVorlage: 'Beim Trinken unterstützen',
    bereichVorlage: 'Ernährung',
    schritte: [
      'Führen und beurteilen der Trinkbilanz',
      'Ausscheidung beurteilen',
      'Anleitung der Klientin oder deren Angehörige über Wichtigkeit, genügend Flüssigkeit aufzunehmen',
    ],
  },
  {
    nr: '10302',
    bezeichnungVorlage: 'Beim Essen helfen',
    bereichVorlage: 'Ernährung',
    schritte: [
      'Anleitung/ Ermunterung zum Essen oder Essen eingeben',
      'Hände der Klientin reinigen/ Mund spülen',
      'Anleitung der Klientin oder deren Angehörige (falls notwendig)',
    ],
  },
  {
    nr: '10303',
    bezeichnungVorlage: 'Instruktion für Essen/Diät',
    bereichVorlage: 'Ernährung',
    schritte: [
      'Beurteilung der üblichen Ernährung der Klientin',
      'Informationen und Motivation für eine ausgeglichene, gesunde Ernährung geben',
      'Klientin oder informelles Netz anleiten',
    ],
  },
  {
    nr: '10304',
    bezeichnungVorlage: 'Sondenernährung',
    bereichVorlage: 'Ernährung',
    schritte: [
      'Notwendige Flüssigkeits- und Nährstoffmenge pro Tag festlegen',
      'Nährlösung vorbereiten',
      'Klientin lagern',
      'Sicherstellen, dass die Magensonde/ PEG-Sonde an korrekter Stelle liegt',
      'Nährlösung an Sonde anschliessen und Ablaufgeschwindigkeit regulieren oder',
      'Nährlösung mit Spritze instillieren',
      'Sonde spülen und Sonde verschliessen',
      'Mund- oder Nasenhöhlen pflegen oder PEG-Verband kontrollieren',
      'Sondenfixierung und Sondenlage kontrollieren',
    ],
  },
  {
    nr: '10305',
    bezeichnungVorlage: 'Einlegen einer Magensonde',
    bereichVorlage: 'Ernährung',
    schritte: [
      'Lagerung der Klientin nach fachlichen Richtlinien',
      'Handschuhe anziehen (nach Richtlinien der Institution)',
      'Sondenlänge messen',
      'Sonde nasal einführen',
      'Überprüfen bzw. sicherstellen, dass die Sonde im Magen liegt',
      'Sonde fixieren',
    ],
  },
  {
    nr: '10306',
    bezeichnungVorlage: 'Gastrostomapflege (PEG-Sonde)',
    bereichVorlage: 'Ernährung',
    schritte: [
      'Lagerung der Klientin',
      'Handschuhe anziehen (nach Richtlinien der Institution)',
      'Entfernung des Materials',
      'Haut um das Stoma reinigen,kontrollieren und pflegen',
      'Neues Material anbringen',
    ],
  },
  {
    nr: '10401',
    bezeichnungVorlage: 'Schüssel / Topf / Steckbecken',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Vorbereitung der Klientin',
      'Handschuhe anziehen',
      'Leere Schüssel bringen, unterschieben, wegnehmen, leeren',
      'Beurteilung des Inhalts',
      'Schüssel, Topf, Steckbecken reinigen',
    ],
  },
  {
    nr: '10402',
    bezeichnungVorlage: 'Urinflasche',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Vorbereitung der Klientin',
      'Handschuhe anziehen',
      'Urinflasche bringen, unterschieben, wegnehmen, leeren',
      'Beurteilung des Inhalts',
    ],
  },
  {
    nr: '10404',
    bezeichnungVorlage: 'Blasenspülung',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Vorbereitung der Klientin',
      'Handschuhe anziehen',
      'Kathetersack entfernen oder Katheterventil öffnen',
      'Unterlegen von Schutzmaterial',
      'Spüllösung auf Körpertemperatur erwärmen',
      'Instillieren',
      'Kontrolle der zurückfliessenden Flüssigkeit (qualitativ, quantitativ)',
      'Urinsack anlegen oder Ventil schliessen',
      'Lage des Kathetersacks kontrollieren',
      'Beim Anziehen helfen',
    ],
  },
  {
    nr: '10405',
    bezeichnungVorlage: 'Urostoma-/ Nephrostomapflege',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Handschuhe anziehen',
      'Unterlegen von Schutzmaterial',
      'Stomasack entfernen',
      'Haut um das Stoma reinigen und trocknen',
      'Hautpflegemittel auftragen, falls indiziert',
      'Neuen Stomasack anbringen',
    ],
  },
  {
    nr: '10406',
    bezeichnungVorlage: 'Pflege/Überwachung Blasenkatheter',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Katheterposition und Urinabfluss kontrollieren',
      'Urinmenge und Qualität kontrollieren',
      'Handschuhe anziehen',
      'Blasenkathetersack wechseln oder leeren',
    ],
  },
  {
    nr: '10407',
    bezeichnungVorlage: 'Blasenkatheter legen, Dauer/Einmal',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Handschuhe anziehen',
      'Intimwäsche',
      'Unterlegen von Schutzmaterial',
      'Einlegen des Katheters',
      'bei Dauerkatheter: Fixation desselben',
      'Ablaufkontrolle',
      'Urinsack anbringen oder Ventil schliessen bzw. Einmalkatheter wieder entfernen',
      'Korrekte Weiterleitung der Urinproben in Arztpraxis oder Labor gewährleist',
    ],
  },
  {
    nr: '10408',
    bezeichnungVorlage: 'Dauerblasenkatheter entfernen',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Handschuhe anziehen',
      'Schutzmaterial unterlegen',
      'Katheterballon mit Spritze entleeren',
      'Katheter ziehen',
    ],
  },
  {
    nr: '10409',
    bezeichnungVorlage: 'Rectalsonde einlegen (Wind)',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Handschuhe anziehen',
      'Schutzmaterial unterlegen',
      'Klientin anleiten',
      'Rectalsonde einführen',
      'Kontrolle des Abdomens',
      'Sonde entfernen',
    ],
  },
  {
    nr: '10410',
    bezeichnungVorlage: 'Practoclyss',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Klientin anleiten',
      'Handschuhe anziehen',
      'Schutzmaterial unterlegen',
      'Practokliss auf Körpertemperatur aufwärmen',
      'Practokliss infundieren',
      'Sonde entfernen',
    ],
  },
  {
    nr: '10411',
    bezeichnungVorlage: 'Einlauf',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Klientin anleiten',
      'Lösung auf Körpertemperatur erwärmen',
      'Handschuhe anziehen',
      'Schutzmaterial unterlegen',
      'Rectalsonde einführen',
      'Lösung infundieren',
      'Kontrolle des Abdomens',
      'Sonde entfernen',
    ],
  },
  {
    nr: '10412',
    bezeichnungVorlage: 'Manuelle Ampullenausräumung',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Eine Stunde vor Ausräumung ein Suppositorium Glycerin verabreichen',
      'Handschuhe anziehen',
      'Schutzmaterial unterlegen',
      'Abdominalmassage',
      'Ausräumung der Ampulle',
      'Reinigung Gesäss',
    ],
  },
  {
    nr: '10413',
    bezeichnungVorlage: 'Anziehen von Einlagen / Urinal anlegen',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Handschuhe anziehen',
      'Gebrauchte Einlagen / gebrauchtes Urinal entfernen',
      'Neue Einlagen einlegen / Urinal anlegen',
      'Klientin anleiten',
    ],
  },
  {
    nr: '10414',
    bezeichnungVorlage: 'Stomasackentleerung',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Handschuhe anziehen',
      'Stomasack leeren oder wechseln',
      'Hautkontrolle',
      'Neuen Stomasack anbringen',
    ],
  },
  {
    nr: '10415',
    bezeichnungVorlage: 'Pflege von Stoma',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Lagerung der Klientin',
      'Schutzmaterial unterlegen',
      'Handschuhe anziehen',
      'Stomasack und Platte entfernen',
      'Haut um das Stoma reinigen und trocknen',
      'Benötigte Creme oder Salbe applizieren',
      'Neue Platte und Stomasack anbringen',
    ],
  },
  {
    nr: '10417',
    bezeichnungVorlage: 'Stomaspülung',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Transfer der Klientin auf Toilette, Nachtstuhl oder Schüssel',
      'Schutzmaterial unterlegen',
      'Handschuhe anziehen',
      'Stomasack entfernen',
      'Darmeingang (Stoma) verifizieren',
      'Spülsystem einführen und Spülung durchführen',
      'Spülsystem entfernen',
      'Haut um das Stoma reinigen und trocknen',
      'Neuen Stomasack anbringen',
    ],
  },
  {
    nr: '10418',
    bezeichnungVorlage: 'Flüssigkeitsbilanz 24h',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Anleitung zum Selber-Führen einer 24-Stunden-Flüssigkeitsbilanz',
      'Kontrolle und Überprüfung des Resultats',
      'Ödeme erkennen und dokumentieren',
      'Arzt informieren',
    ],
  },
  {
    nr: '10419',
    bezeichnungVorlage: 'Begleitung bei Toilettengang',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Auf Toilette/Nachtstuhl begleiten',
      'Beim Aus- und Anziehen helfen',
      'Rufzeichen abmachen und warten',
      'Bei der Reinigung helfen',
      'Ins Zimmer zurück begleiten',
    ],
  },
  {
    nr: '10420',
    bezeichnungVorlage: 'Peritoneal-Dialyse',
    bereichVorlage: 'Ausscheidung',
    schritte: [
      'Installation',
      'Installation des Cyclers oder Anschluss des Dialysates nach Standard',
      'Injektion von Medikamente in die Dialysebeutel',
      'Anschliessen des Cyclers',
      'Start und Funktionskontrolle der Behandlung',
      'Deinstallation',
      'Deinstallation des Cyclers oder des Dialysates',
      'Entnahme von Untersuchungsmaterial zu Laborzwecken',
      'Klinische Überwachung',
      'Materialnachschub sichern',
    ],
  },
  {
    nr: '10501',
    bezeichnungVorlage: 'Lagerung der Klientin im Bett',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Lagerungshilfen aus dem Bett nehmen',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen, Pumpen, Redon, Urinsack, etc.)',
      'Klientin lagern',
      'Lagerungshilfen und Druckschutzhilfen positionieren',
      'In der neuen Position der Klientin sicherstellen, dass technische Instrumente wie Infusionen, Sonden etc. funktionieren',
    ],
  },
  {
    nr: '10502',
    bezeichnungVorlage: 'Lagerung der Klientin im Bett inkl. Bett machen / Bettwäsche wechsel',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Lagerungshilfen aus dem Bett nehmen',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen, Pumpen, Redon, Urinsack, etc.)',
      'Bettwäsche wechseln (falls notwendig)',
      'Klientin lagern',
      'Lagerungshilfen und Druckschutzhilfen positionieren',
      'In der neuen Position der Klientin sicherstellen, dass technische Instrumente wie Infusionen, Sonden etc. funktionieren',
    ],
  },
  {
    nr: '10503',
    bezeichnungVorlage: 'Aufstehen oder Hinlegen mit Hilfe',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Beschreibung "Aufstehen":',
      'Hilfe bei passiver Bewegung im Bett; passive Bettgymnastik (falls notwendig)',
      'Gehhilfen wie Rollator, Stöcke etc. anbieten (ausgenommen Prothesen; s. 10509)',
      'Hilfe bei Transfer auf Lehnstuhl, Rollstuhl o.ä.',
      'Lagerung im Lehnstuhl, Rollstuhl o.ä. und Kontrolle der Haltung',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen,',
      'Pumpen, Redon, Urinsack, etc.)',
      'In der neuen Position der Klientin sicherstellen, dass technische Mittel wie Infusionen, Sonden etc. funktionieren.',
      'Beschreibung "Hinlegen":',
      'Transfer mit Hilfe zurück ins Bett',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen,',
      'Pumpen, Redon, Urinsack, etc.)',
      'Lagerung der Klientin im Bett (falls notwendig)',
      'In der neuen Position der Klientin sicherstellen, dass technische Mittel wie Infusionen, Sonden etc. funktionieren.',
    ],
  },
  {
    nr: '10504',
    bezeichnungVorlage: 'Aufstehen oder Hinlegen mit Lift oder 2 Personen',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Beschreibung "Aufstehen":',
      'ev. Hilfe bei passiver Bewegung im Bett; passive Bettgymnastik',
      'Gehhilfen wie Rollator, Stöcke etc. anbieten (ausgenommen Prothesen; s. 10508)',
      'Hilfe bei Transfer mit Lift oder 2 Personen auf Lehnstuhl, Rollstuhl o.ä.',
      'Lagerung im Lehnstuhl, Rollstuhl o.ä. und Kontrolle der Haltung',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen, Pumpen, Redon, Urinsack, etc.)',
      'In der neuen Position der Klientin sicherstellen, dass technische Mittel wie Infusionen, Sonden etc. funktionieren.',
      'Beschreibung "Hinlegen":',
      'Transfer mit Lift oder 2 Personen zurück ins Bett',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen, Pumpen, Redon, Urinsack, etc.)',
      'ev. Lagerung der Klientin im Bett',
      'In der neuen Position der Klientin sicherstellen, dass technische Mittel wie Infusionen, Sonden etc. funktionieren.',
    ],
  },
  {
    nr: '10505',
    bezeichnungVorlage: 'Hilfe beim Gehen',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Beim Aufstehen helfen.',
      'Gehhilfen wie Rollator, Stöcke etc. anbieten (ausgenommen Prothesen; s. 10508)',
      'Kontrolle der Haltung.',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen, Pumpen, Redon, Urinsack, etc.)',
      'Hilfe beim Gehen in der Wohnung (oder beim Treppensteigen, falls notwendig)',
      'Hilfe beim Absitzen in den Lehnstuhl oder beim Abliegen ins Bett',
      'In der neuen Position der Klientin sicherstellen, dass technische Mittel wie Infusionen, Sonden etc. funktionieren',
    ],
  },
  {
    nr: '10506',
    bezeichnungVorlage: 'Aktive/passive Bewegungsunterstützung',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Ausführung der aktiven/passiven Gelenks- und/oder Muskelbewegungsübungen unter Benützung geeigneter Hilfsmittel',
    ],
  },
  {
    nr: '10507',
    bezeichnungVorlage: 'Gehbegleitung ausserhalb Haus',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Hilfe beim Aussuchen und Anziehen adäquater Kleidung',
      'Gehhilfen wie Rollator, Stöcke etc. anbieten (ausgenommen Prothesen; s. 10508)',
      'Beachten und verschieben von medizinisch technischen Hilfsmitteln (Infusionen,',
      'Pumpen, Redon, Urinsack, etc.)',
      'Nach Heimkehr: Kleider und Hilfsmittel versorgen',
      'Sicherstellen, dass technische Mittel wie Infusionen, Sonden etc. funktionieren.',
    ],
  },
  {
    nr: '10508',
    bezeichnungVorlage: 'Hilfsmittel anbringen oder entfernen',
    bereichVorlage: 'Mobilisation',
    schritte: [
      'Beschreibung "Anbringen":',
      'Körperteil entkleiden',
      'Anbringen des/der Hilfsmittel wie Prothesen, Orthesen, Schienen, Splints, usw.',
      'Kontrolle der korrekten Lage und Funktion des Hilfsmittels',
      'Beschreibung "Entfernen":',
      'Körperteil entkleiden',
      'Entfernen des/der Hilfsmittel wie Prothesen, Orthesen, Schienen, Splints, usw.',
      'Kontrolle und Hautpflege (falls notwendig)',
    ],
  },
  {
    nr: '10601',
    bezeichnungVorlage: 'Medikamente richten',
    bereichVorlage: 'Therapien',
    schritte: [
      'Aktualität und Korrektheit der verordneten Dosierung prüfen',
      'Medikamente in der geeigneten Form für täglichen oder wöchentlichen Bedarf gemäss Arztverordnung bereit machen',
      'Medikamentennachschub sichern',
      'Eventuell führen einer Medikamentennachschubliste für den Arzt oder Apotheker',
      'Aktualisierung der Medikamentenliste sicherstellen',
    ],
  },
  {
    nr: '10602',
    bezeichnungVorlage: 'Verabreichung gerichtete Medikamente',
    bereichVorlage: 'Therapien',
    schritte: [
      'Ärztliche Verordnung konsultieren',
      'Medikamentenverabreichung nach ärztlicher Verordnung',
    ],
  },
  {
    nr: '10603',
    bezeichnungVorlage: 's.c. oder i.m. Medikamentenverabreichung',
    bereichVorlage: 'Therapien',
    schritte: [
      'Arztverordnung konsultieren',
      'Medikamentenprospekt konsultieren (falls notwendig)',
      'Fachgerechte Injektionsvorbereitung',
      'Lagerung der Klientin (falls notwendig)',
      'Fachgerechte Verabreichung des Pharmakons',
      'Reaktion der Klientin beobachten',
    ],
  },
  {
    nr: '10604',
    bezeichnungVorlage: 'i.v. Medikamentenverabreichung',
    bereichVorlage: 'Therapien',
    schritte: [
      'Arztverordnung konsultieren',
      'Medikamentenprospekt konsultieren (falls notwendig)',
      'Lagerung der Klientin (falls notwendig)',
      'Fachgerechte Injektionsvorbereitung',
      'Fachgerechte Venenpunktion und Injektion des Pharmakons',
      'Reaktion der Klientin beobachten',
    ],
  },
  {
    nr: '10605',
    bezeichnungVorlage: 'i.v. Medikamentenverabreichung über Dreiweghahn',
    bereichVorlage: 'Therapien',
    schritte: [
      'Arztverordnung konsultieren',
      'Medikamentenprospekt konsultieren (falls notwendig)',
      'Fachgerechte Injektionsvorbereitung',
      'Klientin lagern',
      'Refluxkontrolle beim Dreiweghahn',
      'Fachgerechte Verabreichung des Pharmakons',
      'Reaktion der Klientin beobachten',
      'Wiedereinfluss der Infusion sicherstellen.',
    ],
  },
  {
    nr: '10606',
    bezeichnungVorlage: 'Infusionstherapie mit Venenpunktion',
    bereichVorlage: 'Therapien',
    schritte: [
      'Arztverordnung konsultieren',
      'Medikamentenprospekt konsultieren (falls notwendig)',
      'Fachgerechte Injektionsvorbereitung',
      'Luftfreie Infusionskanüle mit Venenzugang verbinden',
      'Infusionsgeschwindigkeit regulieren und beobachten',
      'Fixieren des Venenkatheters',
      'Erneut Infusionsgeschwindigkeit kontrollieren',
      'Komfort der Klientin sicherstellen',
      'Beobachtung der Reaktion der Klientin',
    ],
  },
  {
    nr: '10607',
    bezeichnungVorlage: 'Medikamentenverabreichung bei liegendem Venenkatheter/ inkl. Port-a-Cath',
    bereichVorlage: 'Therapien',
    schritte: [
      'Arztverordnung konsultieren',
      'Medikamentenprospekt konsultieren (falls notwendig)',
      'Fachgerechte Injektionsvorbereitung',
      'Blutrückfluss aus liegendem Venenkatheter verifizieren',
      'Fachgerechte Verabreichung des Pharmakons',
      'Komfort der Klientin sicherstellen',
      'Beobachtung der Reaktion der Klientin',
      'Venenkatheter abstöpseln oder ziehen',
    ],
  },
  {
    nr: '10608',
    bezeichnungVorlage: 'Anwesenheit bei Infusionstherapie',
    bereichVorlage: 'Therapien',
    schritte: [
      'Arztverordnung konsultieren',
      'Medikamentenprospekt konsultieren (falls notwendig)',
      'Infusionskontrolle',
      'Kontrolle der Vitalzeichen und Beobachtung der Reaktion der Klientin',
      'Infusion herausziehen oder abstöpseln',
    ],
  },
  {
    nr: '10609',
    bezeichnungVorlage: 'Besuch zur Infusionskontrolle',
    bereichVorlage: 'Therapien',
    schritte: [
      'Kontrolle des Allgemeinzustandes und der Vitalzeichen der Klientin',
      'Sich bei der Klientin oder Ihren Angehörigen über die regelrechte Verabreichung',
      'der Infusion informieren',
      'Blutrückflusskontrolle als Prüfung der korrekten intravenösen Katheterlage',
      'Infusionsgeschwindigkeit kontrollieren',
      'Infusionsstelle kontrollieren',
    ],
  },
  {
    nr: '10610',
    bezeichnungVorlage: 'Bluttransfusion',
    bereichVorlage: 'Therapien',
    schritte: [
      'Blutgruppenkontrolle mit einer Gegenkontrolle durch eine Kollegin',
      'Beachtung der ärztlichen Verordnungen und der Anweisungen des Blutspendezentrums/Labors',
      'Blutbeutel vorbereiten',
      'Fachgerechte Venenpunktion',
      'Luftleere Transfusionsleitung mit Venenzugang verbinden',
      'Fluss der Transfusion kontrollieren',
      'Beobachtung der Reaktion der Klientin',
      'Armposition kontrollieren',
      'Betreuung der Klientin während der Transfusion',
      'Kontrolle der Vitalzeichen vor, während und nach der Transfusion',
      'Fachgerechte Versorgung der Einstichstelle nach Ziehen der Transfusion',
      'Information der Klientin über Verhalten bei Nebenwirkungen (spätere Komplikationen)',
      'Dokumentation der Transfusionsnummer und des Allgemeinzustandes der Klientin',
    ],
  },
  {
    nr: '10612',
    bezeichnungVorlage: 'Anlegen von Dauervenenzugängen',
    bereichVorlage: 'Therapien',
    schritte: [
      'Anlegen von peripheren Dauervenenzugängen (z.B. Butterfly, Venflon, Braunüle',
      'etc.) nach ärztlicher Verordnung',
      'Fachgerechte Venenpunktion und Einlegen Nadel, Kanüle oder Katheter',
      'Fixieren der Kanüle und abstöpseln',
      'Anleitung der Klientin',
    ],
  },
  {
    nr: '10613',
    bezeichnungVorlage: 'Lavage von Kathetern Typ Hickman/Port-a-Cath',
    bereichVorlage: 'Therapien',
    schritte: [
      'Lagerung der Klientin nach Anleitung',
      'Katheterspülung nach Anleitung',
      'Inspektion und evtl. Behandlung der umgebenden Haut',
      'Anleitung der Klientin',
    ],
  },
  {
    nr: '10614',
    bezeichnungVorlage: 's.c. Infusions- oder Pumpentherapie',
    bereichVorlage: 'Therapien',
    schritte: [
      'Beschreibung: Subkutane Infusionstherapie:',
      'Fachgerechte Infusionsvorbereitung',
      'Nach ärztlicher Verordnung evtl. resorbtionsförderndes Medikament zufügen',
      'Fachgerechte Punktion subkutan und Infusion anschliessen',
      'Infusionsfluss kontrollieren',
      'Allgemeinzustand der Klientin kontrollieren',
      'Anleitung der Klientin oder der Angehörigen',
      'Beschreibung: Subkutane Pumpentherapie:',
      'Fachgerechte Infusionsvorbereitung',
      'Fachgerechte Punktion subkutan',
      'Nadel fachgerecht fixieren',
      'Nadel mit Pumpenschlauch verbinden',
      'Parameter der Pumpe nach ärztlicher Anordnung einstellen',
      'Anleitung der Klientin oder der Angehörigen',
    ],
  },
  {
    nr: '10615',
    bezeichnungVorlage: 'Medizinal-Teilbad oder Wickel',
    bereichVorlage: 'Therapien',
    schritte: [
      'Ärztliche Verordnung konsultieren',
      'Wickel oder Medizinal-Teilbad auf gewünschte Temperatur bringen',
      'Lagerung der Klientin oder Wickel applizieren',
      'Überwachung der Klientin während der Applikationszeit',
      'Hilfe beim Abtrocknen und Anziehen',
    ],
  },
  {
    nr: '10616',
    bezeichnungVorlage: 'Massnahmen zur Dekubitusprophylaxe',
    bereichVorlage: 'Therapien',
    schritte: [
      'Massnahme zur Dekubitusprophylaxe durchführen',
      'Lagerung',
    ],
  },
  {
    nr: '10617',
    bezeichnungVorlage: 'Haut einreiben (therapeutisch verordnet)',
    bereichVorlage: 'Therapien',
    schritte: [
      'Zu massierende Körperteile entkleiden',
      'Mittel auftragen und einreiben',
      'Anziehen',
    ],
  },
  {
    nr: '10618',
    bezeichnungVorlage: 'Augentropfen',
    bereichVorlage: 'Therapien',
    schritte: [
      'Augentropfen verabreichen',
    ],
  },
  {
    nr: '10701',
    bezeichnungVorlage: 'Kleiner Verband',
    bereichVorlage: 'Verbände und Hilfsmittel',
    schritte: [
      'Steriles und nicht steriles Material vorbereiten',
      'Steriles oder nicht steriles Feld vorbereiten',
      'Bisherigen Verband wegnehmen',
      'Wunde und die umgebende Haut reinigen und desinfizieren',
      'Wundversorgung gemäss ärztlicher Verordnung',
      'Neuen Verband anbringen und fixieren',
    ],
  },
  {
    nr: '10702',
    bezeichnungVorlage: 'Mittlerer Verband',
    bereichVorlage: 'Verbände und Hilfsmittel',
    schritte: [
      'Steriles und nicht steriles Material vorbereiten',
      'Steriles Feld vorbereiten (falls notwendig)',
      'Bisherigen Verband wegnehmen',
      'Wunde und die umgebende Haut reinigen und desinfizieren',
      'Wundversorgung gemäss ärztlicher Verordnung',
      'Neuen Verband anbringen und fixieren',
    ],
  },
  {
    nr: '10703',
    bezeichnungVorlage: 'Grosser Verband',
    bereichVorlage: 'Verbände und Hilfsmittel',
    schritte: [
      'Steriles und nicht steriles Material vorbereiten',
      'Steriles Feld vorbereiten (falls notwendig)',
      'Bisherigen Verband entfernen',
      'Wunde und die umgebende Haut reinigen und desinfizieren',
      'Wundversorgung gemäss ärztlicher Verordnung',
      'Neuen Verband anbringen und fixieren',
    ],
  },
  {
    nr: '10704',
    bezeichnungVorlage: 'Auslieferung von Hilfsmitteln und Sanitätsmaterial',
    bereichVorlage: 'Verbände und Hilfsmittel',
    schritte: [
      'Lieferung des benötigten Hilfsmittels/Sanitätsmaterials',
      'Funktionsprobe',
      'Quittierung durch Klientin',
    ],
  },
  {
    nr: '10801',
    bezeichnungVorlage: 'Gesundheitskontrolle (Vitalparameter)',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Allgemeinzustand beurteilen',
      'Vitalzeichen (Blutdruck, Puls und Atmung, etc.) messen, beurteilen und dokumentieren',
    ],
  },
  {
    nr: '10802',
    bezeichnungVorlage: 'Blutdruckmessung',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Vorbereitung der Klientin',
      'Blutdruck messen und Messwert dokumentieren',
    ],
  },
  {
    nr: '10803',
    bezeichnungVorlage: 'Pulskontrolle',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Puls kontrollieren und Messwert dokumentieren',
    ],
  },
  {
    nr: '10804',
    bezeichnungVorlage: 'Atmungsbeobachtung und -kontrolle',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Atemzüge pro Zeiteinheit zählen sowie die Atemcharakteristika beurteilen und dokumentieren (Frequenz, Tiefe, Atemgeräusche).',
    ],
  },
  {
    nr: '10805',
    bezeichnungVorlage: 'Temperaturmessung',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Körpertemperatur messen und Messwert dokumentieren',
    ],
  },
  {
    nr: '10806',
    bezeichnungVorlage: 'Gewichtkontrolle',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Klientin möglichst zur selben Zeit und in denselben Kleidern wägen',
      'Ödeme dokumentieren',
    ],
  },
  {
    nr: '10808',
    bezeichnungVorlage: 'Kapillarblutentnahme incl. Glucosebestimmung',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Fachgerechte Vorbereitung und Durchführung der kapillaren Blutentnahme',
      'Apparat für Glucosebestimmung nach Anleitung betätigen oder korrekte Weiterverarbeitung der Blutprobe garantieren',
      'Resultat festhalten',
    ],
  },
  {
    nr: '10809',
    bezeichnungVorlage: 'Venenpunktion',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Laborformular konsultieren',
      'Fachgerechte Vorbereitung des Entnahme- und Beschriftungsmaterials',
      'Fachgerechte Venenpunktion',
      'Notwendige Blutmenge entnehmen',
      'Korrekte Weiterverarbeitung der Blutproben sicherstellen',
    ],
  },
  {
    nr: '10810',
    bezeichnungVorlage: 'Blutentnahme über Zentralvenenkatheter/ Port-a-Cath',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Fachgerechte Lagerung der Klientin',
      'Laborformular konsultieren',
      'Fachgerechte Vorbereitung des Entnahme- und Beschriftungsmaterials',
      'Notwendige Blutmenge entnehmen',
      'Infusion wieder mit Katheter verbinden oder Katheter nach Anleitung spülen',
      'Infusionsflusskontrolle',
      'Korrekte Weiterverarbeitung der Blutproben sicherstellen',
    ],
  },
  {
    nr: '10811',
    bezeichnungVorlage: 'Sekretentnahme zur Analyse',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Fachgerechte Vorbereitung des Entnahme- und Beschriftungsmaterials',
      'Notwendige Sekretmenge entnehmen',
      'Verwendetes Material ordnen und entsorgen',
      'Weiterverarbeitung der Sekretproben sicherstellen',
    ],
  },
  {
    nr: '10812',
    bezeichnungVorlage: 'Urin abnehmen / Uricult anlegen / Glucosebestimmung',
    bereichVorlage: 'Messung Vitalzeichen',
    schritte: [
      'Fachgerechte Vorbereitung des Entnahme- und Beschriftungsmaterials',
      'Notwendige Urinmenge nach Anleitung entnehmen',
      'Durchführen des Glucosetests (falls notwendig)',
      'Weiterverarbeitung der Urinproben sicherstellen (falls notwendig)',
    ],
  },
];

/** Lookup nach KLV-Nummer. */
export const KLV_AUSFUEHRUNGSSCHRITTE_BY_NR: Record<string, KLVAusfuehrungsschritte> =
  Object.fromEntries(KLV_AUSFUEHRUNGSSCHRITTE.map((p) => [p.nr, p]));
