// AUTOGENERIERT – nicht von Hand bearbeiten.
// Quelle: 20211117_LIST_interRAI_HC_Skalen.xlsx (Spitex Schweiz), unverändert übernommen.
//
// `skalierungDe` ist der Wortlaut der Skalierung aus der Quelle, Zeilenumbrüche als \n.
// Numerische Spanne (min/max) und Kategorie sind NICHT Teil dieser Quelle und daher
// hier bewusst nicht enthalten. Sie müssen aus den Algorithmus-Dateien abgeleitet und
// fachlich freigegeben werden, bevor eine Balkendarstellung gebaut wird.

export type SkalaDefinition = {
  readonly algorithmus: string
  readonly titel: string
  readonly skalierungDe: string
}

export const SKALEN_KATALOG: readonly SkalaDefinition[] = [
  {
    algorithmus: 'SUITE9_HS_SCALE_ADLH_2015-03-26.txt',
    titel: 'ADL HIERARCHY SCALE',
    skalierungDe: '0 = UNABHÄNGIG\n1 = AUFSICHT ERFORDERLICH\n2 = BEGRENZTE BEEINTRÄCHTIGUNG\n3 = UMFASSENDE UNTERSTÜTZUNG ERFORDERLICH - 1\n4 = UMFASSENDE UNTERSTÜTZUNG ERFORDERLICH - 2\n5 = ABHÄNGIG\n6 = VÖLLIGE ABHÄNGIGKEIT',
  },
  {
    algorithmus: 'SUITE9_SCALE_ADLLF_G1_V1.0_P_2012-01-31.txt',
    titel: 'ADL LONG FORM SCALE',
    skalierungDe: '0: Keine ADL-Beeinträchtigung\n28: Hohe ADL-Beeinträchtigung.',
  },
  {
    algorithmus: 'SUITE9_HS_SCALE_ADLSF_2015-03-26.txt',
    titel: 'ADL SHORT FORM SCALE',
    skalierungDe: '0: Keine ADL-Beeinträchtigung\n16: Hohe ADL-Beeinträchtigung',
  },
  {
    algorithmus: 'SUITE9_SCALE_AGE_G1_V1.0_P_2012-03-16.txt',
    titel: 'AGE',
    skalierungDe: '',
  },
  {
    algorithmus: 'SUITE9_SCALE_ABS_G1_V1.0_P_2013-10-18a',
    titel: 'AGGRESSIVE BEHAVIOUR SCALE',
    skalierungDe: '0 = KEINE ANZEICHEN VON AGGRESSION\n1-4 = LEICHTE BIS MITTELGRADIGE AGGRESSION\n5+ = SCHWERERE AGGRESSION',
  },
  {
    algorithmus: 'SUITE9_SCALE_BMI_G1_V1.0_P_2012-03-16.txt',
    titel: 'BODY MASS INDEX',
    skalierungDe: '',
  },
  {
    algorithmus: 'SUITE9_SCALE_CPS2_G1_V1.0_P_2017-07-06.txt',
    titel: 'COGNITIVE PERFORMANCE SCALE 2',
    skalierungDe: '0 = INTAKT 1\n1 = INTAKT 2\n2 = BEINAHE INTAKT 1\n3 = BEINAHE INTAKT 2\n4 = MITTELGRADIGE BEEINTRÄCHTIGUNG 1\n5 = MITTELGRADIGE BEEINTRÄCHTIGUNG 2\n6 = SCHWERE BEEINTRÄCHTIGUNG 1\n7 = SCHWERE BEEINTRÄCHTIGUNG 2\n8 = SEHR SCHWERE BEEINTRÄCHTIGUNG',
  },
  {
    algorithmus: 'SUITE9_SCALE_CPS_G1_V1.0_P_2013-10-18.txt',
    titel: 'COGNITIVE PERFORMANCE SCALE 1',
    skalierungDe: 'DIE CPS HAT 7 STUFEN: \n 0 = INTAKT\n1 = BEINAHE INTAKT\n2 = LEICHTE BEEINTRÄCHTIGUNG\n3 = MITTELGRADIGE BEEINTRÄCHTIGUNG\n4 = MITTELGRADIGE ODER SCHWERE BEEINTRÄCHTIGUNG\n5 = SCHWERE BEEINTRÄCHTIGUNG\n6 = SEHR SCHWERE BEEINTRÄCHTIGUNG',
  },
  {
    algorithmus: 'SUITE9_SCALE_COMMUNICATION_G1_V1.0_P_2012-07-23.txt',
    titel: 'COMMUNICATION SCALE',
    skalierungDe: 'HÖHERE WERTE AUF DER SKALA STEHEN FÜR SCHLECHTERE KOMMUNIKATION. \nDIESE SKALA GEHT VON 0 BIS 8: \n 0 = INTAKT\n1 = INTAKT IM GRENZBEREICH\n2 = LEICHTE BEEINTRÄCHTIGUNG\n3 = LEICHTE/MITTELGRADIGE BEEINTRÄCHTIGUNG\n4 = MITTELGRADIGE BEEINTRÄCHTIGUNG\n5 = MITTELGRADIGE/SCHWERE SCHWERE BEEINTRÄCHTIGUNG\n6 = SCHWERE BEEINTRÄCHTIGUNG\n7 = SCHWERE/SEHR SCHWERE BEEINTRÄCHTIGUNG\n8 = SEHR SCHWERE BEEINTRÄCHTIGUNG',
  },
  {
    algorithmus: 'SUITE9_SCALE_DEAFBLIND SEVERITY INDEX_G1_V1.2_P_2015-03-18',
    titel: 'DEAFBLIND SEVERITY INDEX',
    skalierungDe: 'HÖHERE SKALENWERTE STELLEN EINE STÄRKERE BEEINTRÄCHTIGUNG DER SINNE DAR. \nDIESE SKALA GEHT VON 0 BIS 5: \n0 = BEIDE SINNE INTAKT\n1 = EIN SINN INTAKT UND DER ANDERE LEICHT/MITTELGRADIG BEEINTRÄCHTIGT\n2 = EIN SINN INTAKT UND DER ANDERE STARK BEEINTRÄCHTIGT\n3 = BEIDE SINNE LEICHT/MITTELGRADIG BEEINTRÄCHTIGT\n4 = EIN SINN LEICHT/MITTELGRADIG UND DER ANDERE STARK BEEINTRÄCHTIGT\n5 = BEIDE SINNE STARK BEEINTRÄCHTIGT',
  },
  {
    algorithmus: 'SUITE9_SCALE_DRS_G1_V1.0_P_2012-03-16.txt',
    titel: 'DEPRESSION RATING SCALE',
    skalierungDe: 'DIE DRS HAT EINEN BEREICH VON 0 BIS 14. \nPUNKTZAHLEN VON 3 ODER HÖHER WEISEN AUF\nGRÖSSERE ODER KLEINERE DEPRESSIVE STÖRUNGEN HIN.',
  },
  {
    algorithmus: 'SUITE_SCALE_DIVERT_G1_V1.1_P_2017-05-31.txt',
    titel: 'DETECTION OF INDICATORS AND VULNERABILITIES FOR EMERGENCY ROOM TRIPS (DIVERT) SCALE',
    skalierungDe: '1 = NIEDRIGSTES RISIKO EINER ZUKÜNFTIGEN INANSPRUCHNAHME DES NOTDIENSTES\n6 = HÖCHSTES RISIKO EINER ZUKÜNFTIGEN INANSPRUCHNAHME DES NOTDIENSTES',
  },
  {
    algorithmus: 'SUITE9_xFALLS_G1_V1.0_P_2017-01-25.TXT',
    titel: 'RISK OF FALLS',
    skalierungDe: '0 = Kein Sturz in den letzten 90 Tagen\n1 = Kein Sturz in den letzten 30 Tagen, aber fiel innerhalb der 31-90 Tagen\n2 = Ein Sturz in den letzten 30 Tagen\n3 = Zwei und mehr Stürze in den letzten 30 Tagen',
  },
  {
    algorithmus: 'SUITE9_SCALE_FUNCTIONAL_HIERARCHY_V1.1_P_2018-09-20.txt',
    titel: 'ADL-IADL FUNCTIONAL Hierarchy SCALE',
    skalierungDe: 'JE HÖHER DER SKALENWERT, DESTO HÖHER DIE BEEINTRÄCHTIGUNG ZU BEGINN IM BEREICH IADL, DANN DEN IADL UND ADL UND BEI DEN HÖHEREN WERTEN FOKUSSIERT AUF DIE ADL.\n0 = OK\n1 = IADL FRÜH 1\n2 = IADL FRÜH 2\n3 = einige IADL MITTEL 1\n4 = IADL MITTEL 1\n5 = IADL ABHÄNGIG\n6 = 4 IADL-ADL Trans 1\n7 = 5 IADL-ADL Trans 2\n8 = Early ADL \n9 = EINIGE ADL MITTEL 1\n10 = EINIGE ADL MITTEL 1\n11 = ABHÄNGIG ADL',
  },
  {
    algorithmus: 'SUITE9_SCALE_IADL CAPACITY HIERARCHY_V1.0_P_2015-01-16.txt',
    titel: 'IADL CAPACITY HIERARCHY SCALE',
    skalierungDe: '0 = OK - KEINE SCHWIERIGKEIT\n1 = EINIGE SCHWIERIGKEITEN 1\n 2 = EINIGE SCHWIERIGKEITEN 2-3\n3 = EINIGE SCHWIERIGKEITEN 4 PLUS\n4 = GEWISSE ABHÄNGIGKEIT\n5 = HOHE ABHÄNGIGKEIT\n6 = VÖLLIGE ABHÄNGIGKEIT',
  },
  {
    algorithmus: 'SUITE9_SCALE_MAPLE_G1_1.2_P_2017-05-26.TXT',
    titel: 'MAPLE SCALE [METHOD FOR ASSIGNING PRIORITY LEVELS]',
    skalierungDe: 'DER MAPLE-ALGORITHMUS HAT 5 PRIORITÄTSSTUFEN: \n1 = Niedrig\n2 = Leicht\n3 = Mässig\n4 = Hoch\n5 = Sehr hoch',
  },
  {
    algorithmus: 'SUITE9_SCALE_PAIN_G1_V1.0_P_2012-03-16.txt',
    titel: 'PAIN SCALE',
    skalierungDe: 'AUF DER SCHMERZSKALA WIRD ANHAND DER BEIDEN ELEMENTE SCHMERZHÄUFIGKEIT UND SCHMERZSTÄRKE EINE PUNKTZAHL VON 0 BIS 4 WIE FOLGT ERMITTELT: \n(HINWEIS: EINE HÖHERE PUNKTZAHL BEDEUTET STÄRKERE SCHMERZEN)\n0 = KEINE SCHMERZEN\n1 = WENIGER ALS TÄGLICH AUFTRETENDE SCHMERZEN\n2 = TÄGLICH SCHMERZEN, JEDOCH NICHT STARK\n3 = TÄGLICH STARKE SCHMERZEN\n4 = TÄGLICH QUÄLENDE SCHMERZEN',
  },
  {
    algorithmus: 'SUITE9_SCALE_PRESSURE ULCER RISK SCALE_G1_V1.0_P_2012-01-31.txt',
    titel: 'PRESSURE ULCER RISK SCALE',
    skalierungDe: 'DIE PURS HAT 8 STUFEN:\n0 = Sehr geringes Risiko\n1 = Geringes Risiko\n2 = Geringes Risiko\n3 = Mittleres Risiko\n4 = Hohes Risiko\n5 = Hohes Risiko\n6 = Sehr hohes Risiko\n7 = Sehr hohes Risiko\n8 = Sehr hohes Risiko',
  },
] as const
